config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    @tasks = Task.all
  end

  def show
  end

  def create
    @task = Task.create(name: params[:task][:name], description: params[:task][:description], done: params[:task][:done])
  end

  def new
    @task = Task.new
  end

# GET
  def edit
  end

  # POST
  def update
    @task = Task.update(name: params[:task][:name], description: params[:task][:description], done: params[:task][:done])
    # redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :done)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Editing a task</h1>


<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :done %>
  <%= f.check_box :done %>


  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<% @tasks.each do |task|  %>
  <p> <%= task.name %> </p>
  <p> <%= task.description %></p>
  <p> <%= task.done %></p>
  <%= link_to "Delete", task_path(task),
        method: :delete,
        data: { confirm: "Are you sure?" }%>
  <%= link_to "Edit", edit_task_path(task) %>
  <p>------------</p>
<% end %>

app/views/tasks/new.html.erb
<h1>Adding a new task</h1>



<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :done %>
  <%= f.check_box :done %>


  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>SHOW</h1>
<p>Find me in app/views/tasks/show.html.erb</p>
<p> <%= @task.name %> </p>
<p> <%= @task.description %></p>
<p> <%= @task.done %></p>

<%= link_to "All tasks", tasks_path %>

app/views/tasks/update.html.erb
<h1>Update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

<%= link_to "Back to tasks", tasks_path %>
<%= link_to "Back to show", task_path(@task) %>